sudo : reqquired
services :
  - docker

before_install:
  - docker build -t vikas/reactproject -f Dockerfile.dev .

  script:
    - docker run -e CI=true vikas/reactproject npm run test

language: generic 